### ISSUE TITLE
ImageClassification.set_label_from_associated_file not working

### ISSUE THREAD

**Issue by mnishiguchi** [cocoa-xu/tflite_elixir#15]
When writing a [notebook](https://github.com/cocoa-xu/tflite_elixir/blob/main/notebooks/image_classification.livemd) based on the example code in README, I noticed that `ImageClassification.set_label_from_associated_file/2` is not working as expected. Class name won't get added to the inference results.

**Comment by cocoa-xu** [comment]
Hi @mnishiguchi, this function only loads the label file embedded in the model ([associated files](https://www.tensorflow.org/lite/models/convert/metadata#read_the_associated_files_from_models)). 

We can use [`TFLiteElixir.ImageClassification.set_label/2`](https://hexdocs.pm/tflite_elixir/TFLiteElixir.ImageClassification.html#set_label/2) to set labels. 

`TFLiteElixir.ImageClassification.set_label/2` currently expects a list of string as the labels. 

Perhaps we can extend its ability to load a text file directly in the future.

**Comment by mnishiguchi** [comment]
@cocoa-xu Thanks! It totally makes sense. I will add some info in the image classification example.
